export const TESTIMONIALS_DATA = [
    {
        name: 'Alek J.',
        role: 'Client, TopFits',
        avatar: 'https://github.com/leerob.png',
        initials: 'CL',
        rating: 5,
        text: `TopFits was amazing! I found all the right items to resell, everything went smoothly as always. Communication was crystal clear, the process was fast, and I felt confident every step of the way. 10/10 experience. I’ll definitely be coming back to TopFits.`,
    },
    {
        name: 'Alek J.',
        role: 'Client, TopFits',
        avatar: 'https://github.com/leerob.png',
        initials: 'CL',
        rating: 5,
        text: `TopFits was amazing! I found all the right items to resell, everything went smoothly as always. Communication was crystal clear, the process was fast, and I felt confident every step of the way. 10/10 experience. I’ll definitely be coming back to TopFits.`,
    },
    {
        name: 'Alek J.',
        role: 'Client, TopFits',
        avatar: 'https://github.com/leerob.png',
        initials: 'CL',
        rating: 5,
        text: `TopFits was amazing! I found all the right items to resell, everything went smoothly as always. Communication was crystal clear, the process was fast, and I felt confident every step of the way. 10/10 experience. I’ll definitely be coming back to TopFits.`,
    },
    {
        name: 'Alek J.',
        role: 'Client, TopFits',
        avatar: 'https://github.com/leerob.png',
        initials: 'CL',
        rating: 5,
        text: `TopFits was amazing! I found all the right items to resell, everything went smoothly as always. Communication was crystal clear, the process was fast, and I felt confident every step of the way. 10/10 experience. I’ll definitely be coming back to TopFits.`,
    },
    {
        name: 'Alek J.',
        role: 'Client, TopFits',
        avatar: 'https://github.com/leerob.png',
        initials: 'CL',
        rating: 5,
        text: `TopFits was amazing! I found all the right items to resell, everything went smoothly as always. Communication was crystal clear, the process was fast, and I felt confident every step of the way. 10/10 experience. I’ll definitely be coming back to TopFits.`,
    },
    {
        name: 'Alek J.',
        role: 'Client, TopFits',
        avatar: 'https://github.com/leerob.png',
        initials: 'CL',
        rating: 5,
        text: `TopFits was amazing! I found all the right items to resell, everything went smoothly as always. Communication was crystal clear, the process was fast, and I felt confident every step of the way. 10/10 experience. I’ll definitely be coming back to TopFits.`,
    },
];